version: '3.8'
services:
  expressapp:
    container_name: expressapp
    build: ./server
    expose:
      - 8000
    volumes:
      - ./server:/usr/src/app
  reactapp:
    container_name: reactapp
    build: ./frontend
    expose:
      - 5000
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - expressapp
      - reactapp
    restart: always
